# Node.js Express Web App on Linux

# Build a Node.js Express app and deploy it as a Linux web app.

# Add steps that analyze code, save build artifacts, deploy, and more:

# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



trigger:

- master



pool: 'default'



steps:

- task: NodeTool@0

  inputs:

    versionSpec: '10.x'

  displayName: 'Install Node.js'



- script: |

    npm install

    npm build

  displayName: 'npm install and build'



- task: ArchiveFiles@2

  displayName: 'Archive files'

  inputs:

    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false

    archiveType: zip

    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

    replaceExistingArchive: true

    

- task: AzureWebApp@1

  displayName: 'Azure Web App Deploy: expressappyaml'

  inputs:

    azureSubscription: 'CodeLens_Test (6bd70c51-ff44-4c89-9212-8d3f10e2a90a)'

    appType: webAppLinux

    appName: 'TestApp'

    runtimeStack: 'NODE|10.10'

    package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

    startUpCommand: 'npm run start'